### PR TITLE
[MGPG-136] Try the new PR

### LINKED ISSUE #26: Please try with snapshot
Howdy, there is related issue: https://issues.apache.org/jira/browse/MGPG-136
And PR: https://github.com/apache/maven-gpg-plugin/pull/120
And deployed version to apache-snapshots https://repository.apache.org/content/repositories/snapshots/ is 3.2.7-20240923.142458-3

Please try with this version:
* with version bump all should happen again, PR makes plugin "behave as before" by default.
* The try to add to `<passphraseLf>false</passphraseLf>` to NOT append anything to passphrase (see MGPG-99 for context)
* Then try to add (if needed, like gpg spawned process hangs) `<passphraseLf>true</passphraseLf>` that will append LF ONLY (unlike before on Windows CRLF, where GPG expects LF only, and CR most probably caused the pw corruption).

Thanks!

### PR DESCRIPTION
**Pull request by cstamas**
Fixes #26

### CODE REVIEW

**Comment by cstamas** [comment]
This gonna not work, or am unsure, seems like "secret" is not shared for external PRs? If so, pls @ralfkonrad pull this branch into repo and create PR from within it.

**Comment by ralfkonrad** [comment]
Thanks for your effort!

Most likely a security feature that external PRs can't access the secrets. Otherwise, PRs could be used for phishing them.

I'll give it a try tomorrow.

**Comment by cstamas** [comment]
But on thing still bothers me, we do have IT that runs on Windows and enforcer "best practices"... and it never failed. What is the difference?
https://github.com/apache/maven-gpg-plugin/actions/runs/10995225719

This IT:
https://github.com/apache/maven-gpg-plugin/tree/master/src/it/sign-release-best-practices

**Comment by ralfkonrad** [comment]
Looks like it is working: https://github.com/ralfkonrad/test-mvn-gpg-plugin/actions/runs/11010764917/job/30573415886?pr=27#step:9:548

**Comment by ralfkonrad** [comment]
Superseded by #30.

**Pull request closed without merging**
